### ISSUE TITLE
Coveralls CI not working properly

### ISSUE THREAD

**Issue by gkra** [ActiveSCM/vcoworkflows#7]
CI integration with Coveralls does not seem to be working properly.

**Comment by Cheneweth** [comment]
ok - coveralls likes it fine. 79% anyways. Apart from tweaking the badge bit, all i did was uncomment the lines in spec_helper. It just needs a test context to run in. When you add the cucumber tests you will need to add similar...

**Comment by gkra** [comment]
Fixed by #8
